import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./Provider";
import { Children } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bhansa-Gar",
  description: "Generated by create next app",
};

export default function RootLayout({ Children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {Children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
